TestVPCCloudFormPublicRouteAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref TestVPCCloudFormPublicRouteTable
      SubnetId: !Ref TestVPCCloudFormPublicSubnetB