  PublicRouteTable: 
    DependsOn: AttachGateway
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC

#	Syntax
#	
#	To declare this entity in your AWS CloudFormation template, use the following syntax:
#	
#	JSON
#	
#	{
#	  "Type" : "AWS::EC2::RouteTable",
#	  "Properties" : {
#	      "Tags" : [ Tag, ... ],
#	      "VpcId" : String
#	    }
#	}
#	
#	YAML
#	
#	Type: AWS::EC2::RouteTable
#	Properties: 
#	  Tags: 
#	    - Tag
#	  VpcId: String
#	
#	Properties
#	
#	Tags
#	
#	Any tags assigned to the route table.
#	
#	Required: No
#	
#	Type: List of Tag
#	
#	Update requires: No interruption
#	
#	VpcId
#	
#	The ID of the VPC.
#	
#	Required: Yes
#	
#	Type: String
#	
#	Update requires: Replacement
#	
#	Return Values
#	
#	Ref
#	
#	When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the ID of the route table.
#	
#	For more information about using the Ref function, see Ref.
#	
#	Examples
#	
#	Route Table
#	
#	The following example uses the VPC ID from a VPC named myVPC that was declared elsewhere in the same template.
#	
#	JSON
#	
#	"myRouteTable" : {
#	   "Type" : "AWS::EC2::RouteTable",
#	   "Properties" : {
#	      "VpcId" : { "Ref" : "myVPC" },
#	      "Tags" : [ { "Key" : "foo", "Value" : "bar" } ]
#	   }
#	}
#	
#	YAML
#	
#	  myRouteTable:
#	    Type: AWS::EC2::RouteTable
#	    Properties:
#	      VpcId:  
#	        Ref: myVPC
#	      Tags:
#	      - Key: foo
#	        Value: bar
