  PublicDefaultRoute: 
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
#	Syntax
#	
#	To declare this entity in your AWS CloudFormation template, use the following syntax:
#	
#	JSON
#	
#	{
#	  "Type" : "AWS::EC2::Route",
#	  "Properties" : {
#	      "DestinationCidrBlock" : String,
#	      "DestinationIpv6CidrBlock" : String,
#	      "EgressOnlyInternetGatewayId" : String,
#	      "GatewayId" : String,
#	      "InstanceId" : String,
#	      "NatGatewayId" : String,
#	      "NetworkInterfaceId" : String,
#	      "RouteTableId" : String,
#	      "TransitGatewayId" : String,
#	      "VpcPeeringConnectionId" : String
#	    }
#	}
#	
#	YAML
#	
#	Type: AWS::EC2::Route
#	Properties: 
#	  DestinationCidrBlock: String
#	  DestinationIpv6CidrBlock: String
#	  EgressOnlyInternetGatewayId: String
#	  GatewayId: String
#	  InstanceId: String
#	  NatGatewayId: String
#	  NetworkInterfaceId: String
#	  RouteTableId: String
#	  TransitGatewayId: String
#	  VpcPeeringConnectionId: String
#	
#	Properties
#	
#	DestinationCidrBlock
#	
#	The IPv4 CIDR block used for the destination match.
#	
#	You must specify the DestinationCidrBlock or DestinationIpv6CidrBlock property.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: Replacement
#	
#	DestinationIpv6CidrBlock
#	
#	The IPv6 CIDR block used for the destination match.
#	
#	You must specify the DestinationCidrBlock or DestinationIpv6CidrBlock property.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	EgressOnlyInternetGatewayId
#	
#	The ID of the egress-only internet gateway.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	GatewayId
#	
#	The ID of a gateway attached to your VPC.
#	
#	You must specify only one of the following properties: EgressOnlyInternetGatewayId, GatewayId, InstanceId, NatGatewayId, NetworkInterfaceId, or VpcPeeringConnectionId.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	InstanceId
#	
#	The ID of a NAT instance in your VPC.
#	
#	You must specify only one of the following properties: EgressOnlyInternetGatewayId, GatewayId, InstanceId, NatGatewayId, NetworkInterfaceId, or VpcPeeringConnectionId.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	NatGatewayId
#	
#	The ID of a NAT gateway.
#	
#	You must specify only one of the following properties: EgressOnlyInternetGatewayId, GatewayId, InstanceId, NatGatewayId, NetworkInterfaceId, or VpcPeeringConnectionId.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	NetworkInterfaceId
#	
#	The ID of the network interface.
#	
#	You must specify only one of the following properties: EgressOnlyInternetGatewayId, GatewayId, InstanceId, NatGatewayId, NetworkInterfaceId, or VpcPeeringConnectionId.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	RouteTableId
#	
#	The ID of the route table. The routing table must be associated with the same VPC that the virtual private gateway is attached to.
#	
#	Required: Yes
#	
#	Type: String
#	
#	Update requires: Replacement
#	
#	TransitGatewayId
#	
#	The ID of a transit gateway.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	VpcPeeringConnectionId
#	
#	The ID of a VPC peering connection.
#	
#	Required: No
#	
#	Type: String
#	
#	Update requires: No interruption
#	
#	Return Values
#	
#	Ref
#	
#	When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the ID of the route.
#	
#	For more information about using the Ref function, see Ref.
#	
#	Examples
#	
#	Add a Route
#	
#	The following example adds a route that is added to a gateway.
#	
#	JSON
#	
#	"myRoute" : {
#	   "Type" : "AWS::EC2::Route",
#	   "DependsOn" : "GatewayToInternet",
#	   "Properties" : {
#	      "RouteTableId" : { "Ref" : "myRouteTable" },
#	      "DestinationCidrBlock" : "0.0.0.0/0",
#	      "GatewayId" : { "Ref" : "myInternetGateway" }
#	   }
#	}
#	
#	YAML
#	
#	  myRoute:
#	    Type: AWS::EC2::Route
#	    DependsOn: GatewayToInternet
#	    Properties:
#	       RouteTableId:
#	         Ref: myRouteTable
#	       DestinationCidrBlock: 0.0.0.0/0
#	       GatewayId:
#	         Ref: myInternetGateway
