AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets
Resources:
  TestVPCCloudForm:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.101.0/24
      Tags:
        - Key: Name
          Value: TestVPCCloudForm
  TestVPCCloudFormPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 192.168.101.0/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref TestVPCCloudForm
      Tags:
        - Key: Name
          Value: TestVPCCloudFormPublicSubnetA
  TestVPCCloudFormPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 192.168.101.32/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref TestVPCCloudForm
      Tags:
        - Key: Name
          Value: TestVPCCloudFormPrivateSubnetA
  TestVPCCloudFormInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: TestVPCCloudFormInternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref TestVPCCloudFormInternetGateway
      VpcId: !Ref TestVPCCloudForm
  TestVPCCloudFormPublicRouteTable:
    DependsOn: AttachGateway
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TestVPCCloudForm
      Tags:
        - Key: Name
          Value: TestVPCCloudFormPublicRouteTable
  TestVPCCloudFormPublicDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref TestVPCCloudFormInternetGateway
      RouteTableId: !Ref TestVPCCloudFormPublicRouteTable
  TestVPCCloudFormPublicRouteAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TestVPCCloudFormPublicRouteTable
      SubnetId: !Ref TestVPCCloudFormPublicSubnetA
  TestVPCCloudFormPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 192.168.101.16/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref TestVPCCloudForm
      Tags:
        - Key: Name
          Value: TestVPCCloudFormPublicSubnetB
  TestVPCCloudFormPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 192.168.101.48/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref TestVPCCloudForm
      Tags:
        - Key: Name
          Value: TestVPCCloudFormPrivateSubnetB
  TestVPCCloudFormPublicRouteAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TestVPCCloudFormPublicRouteTable
      SubnetId: !Ref TestVPCCloudFormPublicSubnetB
